### ISSUE TITLE
CICD branch is busted

### ISSUE THREAD

**Issue by sedkis** [TykTechnologies/tyk-demo#143]
on `master` branch, when running the `./up.sh tyk2 cicd`, i get an error in `bootstrap.log`

```
No such command import-credentials-as-xml
```

This has been confirmed by @rewsmith 

Looks like the `bootstrap.sh` is using a command `import-cre...` that is available in Jenkins version `2.249.2` but not the newest one that was upgraded to

**Comment by davegarvey** [comment]
Fixed, but now requires Docker Compose v2.
