### ISSUE TITLE
No ACL in the pre defined policies (after bootstrap)

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-demo#44]

**Comment by davegarvey** [comment]
I noticed that the Policies exported by the `export.sh` script do not contain all the expected data. This is something that has changed since v3. Will need further investigation.

**Comment by davegarvey** [comment]
This appears to be fixed in 3.0.1

**Comment by davegarvey** [comment]
Sorry, got this wrong - it's still an issue.

**Comment by davegarvey** [comment]
I've raised an issue here https://tyktech.atlassian.net/browse/TT-479

I believe the problem is that the Dashboard Admin API does not import the data correctly. Am refactoring the bootstrap scripts to try to work around this.
