### ISSUE TITLE
Bootstrap.sh error

### ISSUE THREAD

**Issue by kamniphat01** [TykTechnologies/tyk-demo#88]
Hi guys i would like to ask when i run ./up.sh my bootstrapping getting these error > "ERROR: Request body malformed" 

**Below is my bootstrap.log** 
Fri Jan 22 06:46:44 UTC 2021 Creating Dashboard user groups
Fri Jan 22 06:46:45 UTC 2021   Read-only group:OK
Fri Jan 22 06:46:46 UTC 2021   Default group:OK
Fri Jan 22 06:46:47 UTC 2021   Admin group:OK
Fri Jan 22 06:46:47 UTC 2021 Creating webhooks
Fri Jan 22 06:46:48 UTC 2021   Ok
Fri Jan 22 06:46:48 UTC 2021 Creating Portal for organisation Tyk Demo
Fri Jan 22 06:46:48 UTC 2021   Creating Portal default settings
Fri Jan 22 06:46:48 UTC 2021   Ok
Fri Jan 22 06:46:48 UTC 2021   Initialising Catalogue
Fri Jan 22 06:46:49 UTC 2021   Ok
Fri Jan 22 06:46:49 UTC 2021   Creating Portal home page
Fri Jan 22 06:46:49 UTC 2021   Ok
Fri Jan 22 06:46:49 UTC 2021   Creating Portal user
Fri Jan 22 06:46:50 UTC 2021   Ok
Fri Jan 22 06:46:50 UTC 2021   Creating documentation
Fri Jan 22 06:46:54 UTC 2021   ERROR: Request body malformed

**Comment by Lvceo** [comment]
Which OS are you running?
