### ISSUE TITLE
example of RESTifying graphql using body transform plugin

### ISSUE THREAD

**Issue by sedkis** [TykTechnologies/tyk-demo#97]
body  ransform plugin:
```json
{"query":"query user($userId: Int!) { user(id: $userId) {    name    posts {      title      comments{        name      }    }  } }",
"variables": {
    "userId": {{ .userId }}
}
}
```

url rewrites to:
```
tyk://d0f2c6a67b29457f575203fa951dc12c
```
GraphQL Posts

Example curl:
```
curl --location --request POST 'http://tyk-gateway.localhost:8080/restify/v1/userspostscomments/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "userId": 2
}'

<all the data>
```

**Comment by davegarvey** [comment]
@sedkis thanks for this example 👍 

It seems like this PR breaks the Postman tests for:
- "API Definition / GraphQL / GraphQL - Combine 3 separate REST responses"
- "API Definition / Universal Data Graph / GraphQL - Combine 3 separate REST responses using UDG v2 engine"

They are working on Master, but not in this branch.

Perhaps it's meant to replace them? If so, please commit an updated Postman collection. Thanks!

**Comment by sedkis** [comment]
Will do, thanks :)
